"""Hero assets from the real G80 keychain geometry (run after make_svgs.py and make_images.mjs).

theme/assets/hero-outline.svg   G80 outline, used as the CSS mask for the halftone body
theme/snippets/hero-drl.liquid  inline SVG of the two DRL signatures (pathLength=1 for the draw-on animation)
theme/assets/hero-g80.webp      static end state (no JS / reduced motion): the front render with its chain, cropped so
                                the body lands exactly where the SVG layers and the 3D canvas put it
The hero box CSS (.hero__box > .hero__static: inset -4% -2% -62% -2%) and these crop fractions must match.
"""
import os, re
import numpy as np
from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SVG = os.path.join(ROOT, 'site', 'build', 'svg', 'g80_m3')
THEME = os.path.join(ROOT, 'theme')
EXT = dict(left=0.02, right=0.02, top=0.04, bottom=0.62)


def main():
    outline = open(os.path.join(SVG, 'outline.svg')).read()
    open(os.path.join(THEME, 'assets', 'hero-outline.svg'), 'w').write(outline)
    drl = open(os.path.join(SVG, 'drl.svg')).read()
    vb = re.search(r'viewBox="([^"]+)"', drl).group(1)
    d = re.search(r' d="([^"]+)"', drl).group(1)
    # one path per signature, so they can stagger
    parts = ['M' + p for p in d.split('M') if p.strip()]
    paths = ''.join(f'<path d="{p}" pathLength="1"/>' for p in parts)
    snippet = ('{%- comment -%} Generated by site/tools/make_hero_assets.py from the G80 design map. Do not edit. {%- endcomment -%}\n'
               f'<svg viewBox="{vb}" preserveAspectRatio="xMidYMid meet" focusable="false">{paths}</svg>\n')
    open(os.path.join(THEME, 'snippets', 'hero-drl.liquid'), 'w').write(snippet)

    x0, y0, w_mm, h_mm = map(float, vb.split())        # viewBox already includes the 1 mm margin
    im = Image.open(os.path.join(ROOT, 'site', 'build', 'renders_png', 'g80_m3__white__front-chain.png')).convert('RGBA')
    a = np.array(im)[..., 3] > 16
    rows = np.where(a.any(1))[0]
    cols = np.where(a.any(0))[0]
    widths = a.sum(1)
    body_rows = np.where(widths > 0.4 * (cols.max() - cols.min()))[0]
    top, bottom = rows.min(), body_rows.max()
    left, right = cols.min(), cols.max()
    k = (right - left) / (w_mm - 2)                      # px per mm (body width = viewBox width - 2 mm)
    print('px/mm x', round(k, 2), 'y', round((bottom - top) / (h_mm - 2), 2))
    vx, vy = left - k, top - k
    vw, vh = w_mm * k, h_mm * k
    box = (vx - EXT['left'] * vw, vy - EXT['top'] * vh, vx + (1 + EXT['right']) * vw, vy + (1 + EXT['bottom']) * vh)
    box = tuple(int(round(v)) for v in box)
    canvas = Image.new('RGBA', (box[2] - box[0], box[3] - box[1]), (0, 0, 0, 0))
    canvas.paste(im.crop((max(0, box[0]), max(0, box[1]), min(im.width, box[2]), min(im.height, box[3]))),
                 (max(0, -box[0]), max(0, -box[1])))
    w = 1600
    canvas = canvas.resize((w, round(canvas.height * w / canvas.width)), Image.LANCZOS)
    canvas.save(os.path.join(THEME, 'assets', 'hero-g80.webp'), quality=86, method=6)
    print('hero-g80.webp', canvas.size)


if __name__ == '__main__':
    main()
